# Generated by Django 5.0 on 2023-12-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seed',
            field=models.IntegerField(default=100),
        ),
    ]
