# Generated by Django 5.0 on 2023-12-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seed',
        ),
    ]
